### ISSUE TITLE
Bandit doesnt backstab

### ISSUE THREAD

**Issue by DivineNox** [prodzpod/NotHypercrit#1]
after adding the mod bandit doesn't crit when shooting an enemy's back. just to make sure I restarted my game twice and its definitely this mods doing.

love the mod though really hope this gets fixed.
i made a github account just for this so if i made any fo paux's im very sorry.

edit: he also doesn't appear to be hemorrhaging anymore either.

**Comment by prodzpod** [comment]
just confirmed that bandit does backstab. may have been fixed a few versions ago
