### ISSUE TITLE
Elite Reworks (Voidtouched Rework) Incompat

### ISSUE THREAD

**Issue by Fooshcookie** [prodzpod/NotHypercrit#10]
Running both Hypercrit for SOTS and any Elite Rework that removes collapse, causes it to ignore the rework and apply collapse anyway. I am running specifically Moffein's one. 

Edit I Forgot: Disabling Hypercollapse didn't seem to fix the issue either. 

Please let me know if there is any information I can provide that may help!

**Comment by prodzpod** [comment]
cannot reproduce, maybe its another mod?

**Comment by Fooshcookie** [comment]
Possibly, lemme give it another run really quick and see if I can recreate it again.

**Comment by Fooshcookie** [comment]
Well fuck me, now it's working fine. Guh? Whatever, going to close this. This game hurts my head.
