### ISSUE TITLE
Suggestion: Laser Scope Rework

### ISSUE THREAD

**Issue by gaforb** [prodzpod/NotHypercrit#3]
as an alternative to adding damage, it could just always increase the "level" of a successful crit by 1, as if you had 100% more crit chance. This better respects mod settings like type of scaling and makes the item more distinct from railgunner's passive.

~~Also config for how much crit chance it adds would be nice I guess, 25% might be a bit much sometimes.~~ Nevermind I'm blind

**Comment by prodzpod** [comment]
done
