### ISSUE TITLE
Collapse numbers in BetterUI's stats menu are wrong

### ISSUE THREAD

**Issue by LordVGames** [prodzpod/NotHypercrit#7]
The collapse chance number is shown with a 100x multiplier. For instance, one needletick shows as 1000% chance:
![image](https://github.com/prodzpod/NotHypercrit/assets/51967559/d53e169f-5e93-41e1-a279-1f868955a818)
A single needletick still uses its 10% chance. The bleed and crit numbers don't have this problem.

Each needletick also adds 10 to the hypercollapse number:
![image](https://github.com/prodzpod/NotHypercrit/assets/51967559/4ba5413f-5ea9-4c7a-979a-23a2b0fb360f)
![image](https://github.com/prodzpod/NotHypercrit/assets/51967559/4b04d0ed-b51b-4055-bccb-62a6269e6459)
The bleed and crit numbers don't have this problem either.

**Comment by prodzpod** [comment]
betterui is deprecated now, removed the compat this version
