### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by ExPeerTT** [prodzpod/NotHypercrit#9]
Please update the mystic items mod too, I beg you.

**Comment by prodzpod** [comment]
i dont even know how to contact mystic now

**Comment by prodzpod** [comment]
oh actually the repo is MIT

**Comment by prodzpod** [comment]
hmmm

**Comment by ExPeerTT** [comment]
can you do it? :)))))

**Comment by prodzpod** [comment]
actually it seems like people have tried and failed already, wwise version is updated with sots so recompilation of the soundbank is needed but it is not in the repo (i have all the mods working now without sound)
![12321](https://github.com/user-attachments/assets/c9df326a-758d-453c-9352-2c7fad1f0121)

**Comment by prodzpod** [comment]
unless

**Comment by ExPeerTT** [comment]
Unless??

**Comment by ExPeerTT** [comment]
Would it be possible to post them without audio?

**Comment by prodzpod** [comment]
https://thunderstore.io/package/prodzpod/RealerMysticsItems/

**Comment by ExPeerTT** [comment]
Simply the GOAT prodzpod

**Comment by prodzpod** [comment]
i do what phreeln't
